<?php

use App\Preco;
use Illuminate\Database\Seeder;

class PrecoSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $precos = [
            [
                "id" => 1,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 1
            ],
            [
                "id" => 2,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 1
            ],
            [
                "id" => 3,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 13.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 1
            ],
            [
                "id" => 4,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 1
            ],
            [
                "id" => 5,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 1
            ],
            [
                "id" => 6,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 19.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 1
            ],
            [
                "id" => 7,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 17.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 1
            ],
            [
                "id" => 8,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 21.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 1
            ],
            [
                "id" => 9,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 41.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 1
            ],
            [
                "id" => 10,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 17.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 1
            ],
            [
                "id" => 11,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 13.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 2
            ],
            [
                "id" => 12,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 17.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 2
            ],
            [
                "id" => 13,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 2
            ],
            [
                "id" => 14,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 2
            ],
            [
                "id" => 15,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 15.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 2
            ],
            [
                "id" => 16,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 37.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 2
            ],
            [
                "id" => 17,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 33.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 2
            ],
            [
                "id" => 18,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 41.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 2
            ],
            [
                "id" => 19,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 82.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 2
            ],
            [
                "id" => 20,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 33.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 2
            ],
            [
                "id" => 21,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 15.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 3
            ],
            [
                "id" => 22,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 3
            ],
            [
                "id" => 23,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 37.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 3
            ],
            [
                "id" => 24,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 74.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 3
            ],
            [
                "id" => 25,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 19.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 3
            ],
            [
                "id" => 26,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 55.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 3
            ],
            [
                "id" => 27,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 3
            ],
            [
                "id" => 28,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 61.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 3
            ],
            [
                "id" => 29,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 122.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 3
            ],
            [
                "id" => 30,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 3
            ],
            [
                "id" => 31,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 17.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 4
            ],
            [
                "id" => 32,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 33.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 4
            ],
            [
                "id" => 33,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 4
            ],
            [
                "id" => 34,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 98.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 4
            ],
            [
                "id" => 35,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 4
            ],
            [
                "id" => 36,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 74.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 4
            ],
            [
                "id" => 37,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 65.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 4
            ],
            [
                "id" => 38,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 82.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 4
            ],
            [
                "id" => 39,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 163.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 4
            ],
            [
                "id" => 40,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 65.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 4
            ],
            [
                "id" => 41,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 5
            ],
            [
                "id" => 42,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 5
            ],
            [
                "id" => 43,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 74.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 5
            ],
            [
                "id" => 44,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 147.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 5
            ],
            [
                "id" => 45,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 37.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 5
            ],
            [
                "id" => 46,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 110.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 5
            ],
            [
                "id" => 47,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 98.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 5
            ],
            [
                "id" => 48,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 122.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 5
            ],
            [
                "id" => 49,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 244.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 5
            ],
            [
                "id" => 50,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 98.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 5
            ],
            [
                "id" => 51,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 34.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 6
            ],
            [
                "id" => 52,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 65.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 6
            ],
            [
                "id" => 53,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 98.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 6
            ],
            [
                "id" => 54,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 195.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 6
            ],
            [
                "id" => 55,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 6
            ],
            [
                "id" => 56,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 147.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 6
            ],
            [
                "id" => 57,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 130.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 6
            ],
            [
                "id" => 58,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 163.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 6
            ],
            [
                "id" => 59,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 325.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 6
            ],
            [
                "id" => 60,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 130.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 6
            ],
            [
                "id" => 61,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 41.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 7
            ],
            [
                "id" => 62,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 82.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 7
            ],
            [
                "id" => 63,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 122.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 7
            ],
            [
                "id" => 64,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 244.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 7
            ],
            [
                "id" => 65,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 61.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 7
            ],
            [
                "id" => 66,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 183.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 7
            ],
            [
                "id" => 67,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 163.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 7
            ],
            [
                "id" => 68,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 204.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 7
            ],
            [
                "id" => 69,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 407.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 7
            ],
            [
                "id" => 70,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 163.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 7
            ],
            [
                "id" => 71,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 82.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 1,
                "quantidade_id" => 8
            ],
            [
                "id" => 72,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 163.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 2,
                "quantidade_id" => 8
            ],
            [
                "id" => 73,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 244.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 3,
                "quantidade_id" => 8
            ],
            [
                "id" => 74,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 489.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 4,
                "quantidade_id" => 8
            ],
            [
                "id" => 75,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 122.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 5,
                "quantidade_id" => 8
            ],
            [
                "id" => 76,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 366.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 6,
                "quantidade_id" => 8
            ],
            [
                "id" => 77,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 325.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 7,
                "quantidade_id" => 8
            ],
            [
                "id" => 78,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 407.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 8,
                "quantidade_id" => 8
            ],
            [
                "id" => 79,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 813.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 9,
                "quantidade_id" => 8
            ],
            [
                "id" => 80,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => null,
                "preco" => 325.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 1,
                "medida_id" => 10,
                "quantidade_id" => 8
            ],
            [
                "id" => 81,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 19.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 11,
                "quantidade_id" => null
            ],
            [
                "id" => 82,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 25.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 12,
                "quantidade_id" => null
            ],
            [
                "id" => 83,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 38.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 13,
                "quantidade_id" => null
            ],
            [
                "id" => 84,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 60.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 14,
                "quantidade_id" => null
            ],
            [
                "id" => 85,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 90.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 15,
                "quantidade_id" => null
            ],
            [
                "id" => 86,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 16.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 16,
                "quantidade_id" => null
            ],
            [
                "id" => 87,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 34.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 17,
                "quantidade_id" => null
            ],
            [
                "id" => 88,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 60.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 18,
                "quantidade_id" => null
            ],
            [
                "id" => 89,
                "impressao" => null,
                "tem_acabamento" => "SN",
                "tipo_acabamento" => "",
                "preco" => 74.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 2,
                "medida_id" => 19,
                "quantidade_id" => null
            ],
            [
                "id" => 90,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 70.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 3,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 91,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 50.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 3,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 92,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 70.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 4,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 93,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 50.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 4,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 94,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 50.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 5,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 95,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 115.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 6,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 96,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 100.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 6,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 97,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 115.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 7,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 98,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 100.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 7,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 99,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 115.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 8,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 100,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 100.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 8,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 101,
                "impressao" => null,
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 115.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 9,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 102,
                "impressao" => null,
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 100.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 9,
                "medida_id" => null,
                "quantidade_id" => null
            ],
            [
                "id" => 103,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 210.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 104,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 270.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 105,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 270.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 106,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 352.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 107,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 106.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 108,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 138.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 109,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 134.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 110,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 174.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 111,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 112,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 70.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 113,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 69.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 114,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 88.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 115,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 26.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 116,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 34.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 117,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 34.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 118,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 44.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 119,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 16.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 120,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 19.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 121,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 19.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 122,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 28.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 123,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 124,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 11.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 125,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 11.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 126,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 16.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 127,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 7.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 128,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 129,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 130,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 14.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 131,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 6.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 132,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 133,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 134,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 13.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 135,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 5.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 136,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 137,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 138,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 12.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 10,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 139,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 148.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 140,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 232.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 141,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 210.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 142,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 258.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 143,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 74.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 144,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 98.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 145,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 96.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 146,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 128.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 147,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 36.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 148,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 44.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 149,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 44.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 150,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 49.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 151,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 19.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 152,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 24.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 153,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 24.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 154,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 28.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 155,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 14.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 156,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 18.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 157,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 18.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 158,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 24.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 159,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 160,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 161,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 162,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 14.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 163,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 6.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 164,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 165,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 166,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 13.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 167,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 5.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 168,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 169,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 170,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 12.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 171,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 4.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 172,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 173,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 7.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 174,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 11,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 175,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 130.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 176,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 178.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 177,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 178.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 178,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 230.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 20,
                "quantidade_id" => null
            ],
            [
                "id" => 179,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 64.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 180,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 94.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 181,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 88.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 182,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 110.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 21,
                "quantidade_id" => null
            ],
            [
                "id" => 183,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 32.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 184,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 40.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 185,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 40.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 186,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 45.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 22,
                "quantidade_id" => null
            ],
            [
                "id" => 187,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 15.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 188,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 20.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 189,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 22.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 190,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 24.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 23,
                "quantidade_id" => null
            ],
            [
                "id" => 191,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 192,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 11.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 193,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 11.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 194,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 16.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 24,
                "quantidade_id" => null
            ],
            [
                "id" => 195,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 6.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 196,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 197,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 198,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 13.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 25,
                "quantidade_id" => null
            ],
            [
                "id" => 199,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 5.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 200,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 8.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 201,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 8.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 202,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 12.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 26,
                "quantidade_id" => null
            ],
            [
                "id" => 203,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 5.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 204,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 205,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 8.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 206,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 10.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 27,
                "quantidade_id" => null
            ],
            [
                "id" => 207,
                "impressao" => "F",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 4.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 208,
                "impressao" => "F",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 7.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 209,
                "impressao" => "FV",
                "tem_acabamento" => "N",
                "tipo_acabamento" => "",
                "preco" => 7.5,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 28,
                "quantidade_id" => null
            ],
            [
                "id" => 210,
                "impressao" => "FV",
                "tem_acabamento" => "S",
                "tipo_acabamento" => "",
                "preco" => 9.0,
                "created_at" => null,
                "updated_at" => null,
                "material_id" => 12,
                "medida_id" => 28,
                "quantidade_id" => null
            ]
        ];

        Preco::insert($precos);


    }
}
